services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=lambda,apigateway
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
